#!/bin/sh

rust=$2
tools=$3
: ${rust:="$HOME/pi-rust"}
: ${tools:="$HOME/pi-tools"}

export LD_LIBRARY_PATH="$rust/lib":$LD_LIBRARY_PATH
export PATH="$rust/bin":"$tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin":$PATH

if [ "$1" != "doc" ]
then
	flags="--target=arm-unknown-linux-gnueabihf"
fi

cargo $1 $flags