#!/bin/sh

tools=$2
: ${tools:="$HOME/pi-tools"}

export SYSROOT="$tools/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot"

#Include the cross copilation binaries
export PATH="$tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin":$PATH

#Set up our tools for anyting using these variables
export CC="$tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot"
export AR="$tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar"

#Set target triple
flags="--target=arm-unknown-linux-gnueabihf"

if [ "$1" != "-v" ]
then
	cargo $1 $flags
else
	rustc -vV
fi
